
project: 'hypercellularity'
n_folds: 5
seed: 42
num_workers: 0
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 40
wandb_on: True
model_name: 'Hypercellularity'
data_dir: './data/binary/Hypercellularity/'
classes: ['_others', 'Hypercellularity']