
project: 'model-binary-glomerulus-hypercellularity'
n_folds: 5
seed: 42
num_workers: 0
batch_size: 128
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 15
wandb_on: True
model_name: 'hiper_others'
data_dir: './data/binary/hiper_others/'
classes: ['hipercelularity', 'others']
data_folders:
  - '..\data\binary\hiper_others\hipercellularity'
  - '..\data\binary\hiper_others\others'
  - '..\data\binary\hiper_others\hipercellularity\AZAN'
  - '..\data\binary\hiper_others\hipercellularity\HE'
  - '..\data\binary\hiper_others\hipercellularity\PAS'
  - '..\data\binary\hiper_others\hipercellularity\PS'
  - '..\data\binary\hiper_others\others\membranous'
  - '..\data\binary\hiper_others\others\normal'
  - '..\data\binary\hiper_others\others\sclerosis'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous\HE'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous\PAS'
  - '..\data\binary\hiper_others\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\hiper_others\others\normal\AZAN'
  - '..\data\binary\hiper_others\others\normal\HE'
  - '..\data\binary\hiper_others\others\normal\PAMS'
  - '..\data\binary\hiper_others\others\normal\PAS'
  - '..\data\binary\hiper_others\others\normal\PICRO'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis\HE'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\hiper_others\others\sclerosis\sclerosis_withoutMemb\PS'