
project: 'model-binary-glomerulus-normal'
n_folds: 5
seed: 42
num_workers: 4
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 80
wandb_on: True
wandb_key: '273b6e50d83b95fd3a12d6544e5d48bf5afa49e2'
model_name: 'normal'
data_dir: './data/processed/normal/'
classes: ['normal', 'others']
data_folders:
  - '..\data\binary\normal\normal'
  - '..\data\binary\normal\others'
  - '..\data\binary\normal\normal\AZAN'
  - '..\data\binary\normal\normal\HE'
  - '..\data\binary\normal\normal\PAMS'
  - '..\data\binary\normal\normal\PAS'
  - '..\data\binary\normal\normal\PICRO'
  - '..\data\binary\normal\others\hipercellularity'
  - '..\data\binary\normal\others\membranous'
  - '..\data\binary\normal\others\sclerosis'
  - '..\data\binary\normal\others\hipercellularity\AZAN'
  - '..\data\binary\normal\others\hipercellularity\HE'
  - '..\data\binary\normal\others\hipercellularity\PAS'
  - '..\data\binary\normal\others\hipercellularity\PS'
  - '..\data\binary\normal\others\membranous\primary_membranous'
  - '..\data\binary\normal\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\normal\others\membranous\primary_membranous\HE'
  - '..\data\binary\normal\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\normal\others\membranous\primary_membranous\PAS'
  - '..\data\binary\normal\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\normal\others\sclerosis\sclerosis'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\normal\others\sclerosis\sclerosis\HE'
  - '..\data\binary\normal\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\normal\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\normal\others\sclerosis\sclerosis_withoutMemb\PS'