
project: 'model-binary-glomerulus-podocytopathy'
n_folds: 5
seed: 42
num_workers: 4
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 40
wandb_on: True
wandb_key: '273b6e50d83b95fd3a12d6544e5d48bf5afa49e2'
model_name: 'Podocitopatia'
data_dir: './data/binary/binary_Podocitopatia'
classes: ['_others', 'Podocitopatia']
data_folders:
  - '..\data\binary\podocytopathy\others'
  - '..\data\binary\podocytopathy\_podocitopatia'
  - '..\data\binary\podocytopathy\others\Crescentes'
  - '..\data\binary\podocytopathy\others\hipercellularity'
  - '..\data\binary\podocytopathy\others\membranous'
  - '..\data\binary\podocytopathy\others\normal'
  - '..\data\binary\podocytopathy\others\sclerosis'
  - '..\data\binary\podocytopathy\others\Crescentes\AZAN'
  - '..\data\binary\podocytopathy\others\Crescentes\H_E'
  - '..\data\binary\podocytopathy\others\Crescentes\PAMS'
  - '..\data\binary\podocytopathy\others\Crescentes\PAS'
  - '..\data\binary\podocytopathy\others\Crescentes\PICRO'
  - '..\data\binary\podocytopathy\others\Crescentes\PS'
  - '..\data\binary\podocytopathy\others\hipercellularity\AZAN'
  - '..\data\binary\podocytopathy\others\hipercellularity\HE'
  - '..\data\binary\podocytopathy\others\hipercellularity\PAS'
  - '..\data\binary\podocytopathy\others\hipercellularity\PS'
  - '..\data\binary\podocytopathy\others\hipercellularity\PSA'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous\HE'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous\PAS'
  - '..\data\binary\podocytopathy\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous\AZAN'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous\HE'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous\PAMS'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous\PAS'
  - '..\data\binary\podocytopathy\others\membranous\secondary_membranous\PICRO'
  - '..\data\binary\podocytopathy\others\normal\AZAN'
  - '..\data\binary\podocytopathy\others\normal\HE'
  - '..\data\binary\podocytopathy\others\normal\PAMS'
  - '..\data\binary\podocytopathy\others\normal\PAS'
  - '..\data\binary\podocytopathy\others\normal\PICRO'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis\HE'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\podocytopathy\others\sclerosis\sclerosis_withoutMemb\PS'
  - '..\data\binary\podocytopathy\_podocitopatia\With'
  - '..\data\binary\podocytopathy\_podocitopatia\With\AZAN'
  - '..\data\binary\podocytopathy\_podocitopatia\With\HE'
  - '..\data\binary\podocytopathy\_podocitopatia\With\PAMS'
  - '..\data\binary\podocytopathy\_podocitopatia\With\PAS'
  - '..\data\binary\podocytopathy\_podocitopatia\With\PICRO'