
project: 'model-binary-glomerulus-podocytopathy'
n_folds: 5
seed: 42
num_workers: 0
batch_size: 128
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 15
wandb_on: True
model_name: 'podoc_others'
data_dir: './data/binary/podoc_others/'
classes: ['podocytopathy', 'others']
data_folders:
  - '..\data\binary\podoc_others\others'
  - '..\data\binary\podoc_others\_podocitopatia'
  - '..\data\binary\podoc_others\others\Crescentes'
  - '..\data\binary\podoc_others\others\hipercellularity'
  - '..\data\binary\podoc_others\others\membranous'
  - '..\data\binary\podoc_others\others\normal'
  - '..\data\binary\podoc_others\others\sclerosis'
  - '..\data\binary\podoc_others\others\Crescentes\AZAN'
  - '..\data\binary\podoc_others\others\Crescentes\H_E'
  - '..\data\binary\podoc_others\others\Crescentes\PAMS'
  - '..\data\binary\podoc_others\others\Crescentes\PAS'
  - '..\data\binary\podoc_others\others\Crescentes\PICRO'
  - '..\data\binary\podoc_others\others\Crescentes\PS'
  - '..\data\binary\podoc_others\others\hipercellularity\AZAN'
  - '..\data\binary\podoc_others\others\hipercellularity\HE'
  - '..\data\binary\podoc_others\others\hipercellularity\PAS'
  - '..\data\binary\podoc_others\others\hipercellularity\PS'
  - '..\data\binary\podoc_others\others\hipercellularity\PSA'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous\HE'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous\PAS'
  - '..\data\binary\podoc_others\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous\AZAN'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous\HE'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous\PAMS'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous\PAS'
  - '..\data\binary\podoc_others\others\membranous\secondary_membranous\PICRO'
  - '..\data\binary\podoc_others\others\normal\AZAN'
  - '..\data\binary\podoc_others\others\normal\HE'
  - '..\data\binary\podoc_others\others\normal\PAMS'
  - '..\data\binary\podoc_others\others\normal\PAS'
  - '..\data\binary\podoc_others\others\normal\PICRO'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis\HE'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\podoc_others\others\sclerosis\sclerosis_withoutMemb\PS'
  - '..\data\binary\podoc_others\_podocitopatia\With'
  - '..\data\binary\podoc_others\_podocitopatia\With\AZAN'
  - '..\data\binary\podoc_others\_podocitopatia\With\HE'
  - '..\data\binary\podoc_others\_podocitopatia\With\PAMS'
  - '..\data\binary\podoc_others\_podocitopatia\With\PAS'
  - '..\data\binary\podoc_others\_podocitopatia\With\PICRO'