
project: 'model-binary-glomerulus-crescent'
n_folds: 5
seed: 42
num_workers: 4
batch_size: 64
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 80
wandb_on: True
wandb_key: '273b6e50d83b95fd3a12d6544e5d48bf5afa49e2'
model_name: 'crescent'
data_dir: './data/processed/crescent/'
classes: ['crescent', 'others']
data_folders:
  - '..\data\binary\crescent\crescentes'
  - '..\data\binary\crescent\others'
  - '..\data\binary\crescent\crescentes\AZAN'
  - '..\data\binary\crescent\crescentes\H_E'
  - '..\data\binary\crescent\crescentes\PAMS'
  - '..\data\binary\crescent\crescentes\PAS'
  - '..\data\binary\crescent\crescentes\PICRO'
  - '..\data\binary\crescent\crescentes\PS'
  - '..\data\binary\crescent\others\hipercellularity'
  - '..\data\binary\crescent\others\membranous'
  - '..\data\binary\crescent\others\normal'
  - '..\data\binary\crescent\others\Podocitopatia_stain'
  - '..\data\binary\crescent\others\sclerosis'
  - '..\data\binary\crescent\others\hipercellularity\AZAN'
  - '..\data\binary\crescent\others\hipercellularity\HE'
  - '..\data\binary\crescent\others\hipercellularity\PAS'
  - '..\data\binary\crescent\others\hipercellularity\PS'
  - '..\data\binary\crescent\others\hipercellularity\PSA'
  - '..\data\binary\crescent\others\membranous\primary_membranous'
  - '..\data\binary\crescent\others\membranous\secondary_membranous'
  - '..\data\binary\crescent\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\crescent\others\membranous\primary_membranous\HE'
  - '..\data\binary\crescent\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\crescent\others\membranous\primary_membranous\PAS'
  - '..\data\binary\crescent\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\crescent\others\membranous\secondary_membranous\AZAN'
  - '..\data\binary\crescent\others\membranous\secondary_membranous\HE'
  - '..\data\binary\crescent\others\membranous\secondary_membranous\PAMS'
  - '..\data\binary\crescent\others\membranous\secondary_membranous\PAS'
  - '..\data\binary\crescent\others\membranous\secondary_membranous\PICRO'
  - '..\data\binary\crescent\others\normal\AZAN'
  - '..\data\binary\crescent\others\normal\HE'
  - '..\data\binary\crescent\others\normal\PAMS'
  - '..\data\binary\crescent\others\normal\PAS'
  - '..\data\binary\crescent\others\normal\PICRO'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With\AZAN'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With\HE'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With\PAMS'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With\PAS'
  - '..\data\binary\crescent\others\Podocitopatia_stain\With\PICRO'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without\AZAN'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without\HE'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without\PAMS'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without\PAS'
  - '..\data\binary\crescent\others\Podocitopatia_stain\Without\PICRO'
  - '..\data\binary\crescent\others\sclerosis\sclerosis'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\crescent\others\sclerosis\sclerosis\HE'
  - '..\data\binary\crescent\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\crescent\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\crescent\others\sclerosis\sclerosis_withoutMemb\PS'