
project: 'model-binary-glomerulus-crescente'
n_folds: 5
seed: 42
num_workers: 0
batch_size: 128
pin_memory: True
load_model: False
checkpoint_to_be_loaded: './artifacts/model/my_checkpoint.pth.tar'
learning_rate: 0.0001
num_epochs: 15
wandb_on: True
model_name: 'cresc_others'
data_dir: './data/binary/cresc_others/'
classes: ['crescente', 'others']
data_folders:
  - '..\data\binary\cresc_others\crescentes'
  - '..\data\binary\cresc_others\others'
  - '..\data\binary\cresc_others\crescentes\AZAN'
  - '..\data\binary\cresc_others\crescentes\H_E'
  - '..\data\binary\cresc_others\crescentes\PAMS'
  - '..\data\binary\cresc_others\crescentes\PAS'
  - '..\data\binary\cresc_others\crescentes\PICRO'
  - '..\data\binary\cresc_others\crescentes\PS'
  - '..\data\binary\cresc_others\others\hipercellularity'
  - '..\data\binary\cresc_others\others\membranous'
  - '..\data\binary\cresc_others\others\normal'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain'
  - '..\data\binary\cresc_others\others\sclerosis'
  - '..\data\binary\cresc_others\others\hipercellularity\AZAN'
  - '..\data\binary\cresc_others\others\hipercellularity\HE'
  - '..\data\binary\cresc_others\others\hipercellularity\PAS'
  - '..\data\binary\cresc_others\others\hipercellularity\PS'
  - '..\data\binary\cresc_others\others\hipercellularity\PSA'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous\AZAN'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous\HE'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous\PAMS'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous\PAS'
  - '..\data\binary\cresc_others\others\membranous\primary_membranous\PICRO'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous\AZAN'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous\HE'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous\PAMS'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous\PAS'
  - '..\data\binary\cresc_others\others\membranous\secondary_membranous\PICRO'
  - '..\data\binary\cresc_others\others\normal\AZAN'
  - '..\data\binary\cresc_others\others\normal\HE'
  - '..\data\binary\cresc_others\others\normal\PAMS'
  - '..\data\binary\cresc_others\others\normal\PAS'
  - '..\data\binary\cresc_others\others\normal\PICRO'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With\AZAN'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With\HE'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With\PAMS'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With\PAS'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\With\PICRO'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without\AZAN'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without\HE'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without\PAMS'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without\PAS'
  - '..\data\binary\cresc_others\others\Podocitopatia_stain\Without\PICRO'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis\HE'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis\PAMS'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis\PAS'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb\AZAN'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb\HE'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb\PAMS'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb\PAS'
  - '..\data\binary\cresc_others\others\sclerosis\sclerosis_withoutMemb\PS'